export const CONTACTS_REQUEST = 'CONTACTS_REQUEST';
export const CONTACTS_SUCCESS = 'CONTACTS_SUCCESS';
export const CONTACTS_ERROR = 'CONTACTS_ERROR';

export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';